# Generated by Django 3.2.13 on 2022-10-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_projet', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250, unique=True)),
                ('date_creation', models.CharField(max_length=200)),
            ],
        ),
    ]
