# Generated by Django 3.2.13 on 2022-10-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='statut',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='utilisateur',
            field=models.IntegerField(null=True),
        ),
    ]
